-- Active: 1713861330832@@127.0.0.1@3306@MHS
/*
DROP TABLE MAKES_APPOINTMENT;
DROP TABLE TREATS;
DROP TABLE INVOICE_DETAIL;
DROP TABLE INVOICE;
DROP TABLE PATIENT;
DROP TABLE OUTPATIENT_SURGERY;
DROP TABLE OFFICE_BUILDING;
DROP TABLE NURSE;
DROP TABLE OTHER_HCP;
DROP TABLE DOCTOR;
DROP TABLE ADMIN_STAFF;
DROP TABLE EMPLOYEE;
DROP TABLE FACILITY;
DROP TABLE INSURANCE_COMPANY;
*/

CREATE TABLE FACILITY (
    Facility_ID VARCHAR(255) PRIMARY KEY,
    Street VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(2),
    Zip VARCHAR(10),
    MaxSize INT,
    Facility_Type VARCHAR(50)
);

CREATE TABLE OFFICE_BUILDING (
    Facility_ID VARCHAR(255) PRIMARY KEY REFERENCES FACILITY(Facility_ID),
    Office_Count INT
);

CREATE TABLE OUTPATIENT_SURGERY (
    Facility_ID VARCHAR(255) PRIMARY KEY REFERENCES FACILITY(Facility_ID),
    Room_Count INT,
    Procedure_Code VARCHAR(255),
    Description VARCHAR(1000)
);

CREATE TABLE EMPLOYEE (
    EmployeeID VARCHAR(255) PRIMARY KEY,
    SSN VARCHAR(11) UNIQUE,
    FirstName VARCHAR(255),
    MiddleName VARCHAR(255),
    LastName VARCHAR(255),
    Street VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(255),
    Zip VARCHAR(10),
    Salary DECIMAL(10, 2),
    Date_Hired DATE,
    Job_Class VARCHAR(50),
    Fac_ID VARCHAR(255) REFERENCES FACILITY(Facility_ID)
);

CREATE TABLE DOCTOR (
    EmployeeID VARCHAR(255) PRIMARY KEY REFERENCES EMPLOYEE(EmployeeID),
    Speciality VARCHAR(255),
    Board_Certification_Date DATE
);

CREATE TABLE NURSE (
    EmployeeID VARCHAR(255) PRIMARY KEY REFERENCES EMPLOYEE(EmployeeID),
    Certification VARCHAR(255)
);

CREATE TABLE OTHER_HCP (
    EmployeeID VARCHAR(255) PRIMARY KEY REFERENCES EMPLOYEE(EmployeeID),
    Practice_Area VARCHAR(255)
);

CREATE TABLE ADMIN_STAFF (
    EmployeeID VARCHAR(255) PRIMARY KEY REFERENCES EMPLOYEE(EmployeeID),
    Job_Title VARCHAR(255)
);


CREATE TABLE INSURANCE_COMPANY (
    InsuranceComp_ID VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Street VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(2),
    Zip VARCHAR(10)
);

CREATE TABLE PATIENT (
    Patient_ID VARCHAR(255) PRIMARY KEY,
    FirstName VARCHAR(255),
    MiddleName VARCHAR(255),
    LastName VARCHAR(255),
    Street VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(2),
    Zip VARCHAR(10),
    First_Visit_Date DATE,
    Doctor_ID VARCHAR(255) REFERENCES DOCTOR(EmployeeID),
    InComp_ID VARCHAR(255) REFERENCES INSURANCE_COMPANY(InsuranceComp_ID)
);

CREATE TABLE TREATS (
    Patient_ID VARCHAR(255),
    Doctor_ID VARCHAR(255),
    PRIMARY KEY (Patient_ID, Doctor_ID),
    FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
    FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(EmployeeID)
);

CREATE TABLE INVOICE (
    Inv_ID VARCHAR(255) PRIMARY KEY,
    InvDate DATE,
    InComp_ID VARCHAR(255) REFERENCES INSURANCE_COMPANY(InsuranceComp_ID)
);

CREATE TABLE INVOICE_DETAIL (
    InvDetailID VARCHAR(255) PRIMARY KEY,
    Cost DECIMAL(10, 2),
    Inv_ID VARCHAR(255) REFERENCES INVOICE(Inv_ID)
);


CREATE TABLE MAKES_APPOINTMENT (
    Pat_ID VARCHAR(255),
    Doc_ID VARCHAR(255),
    Fac_ID VARCHAR(255),
    Date_Time TIMESTAMP,
    In_ID VARCHAR(255),
    PRIMARY KEY (Pat_ID, Doc_ID, Fac_ID, Date_Time),
    FOREIGN KEY (Pat_ID) REFERENCES PATIENT(Patient_ID),
    FOREIGN KEY (Doc_ID) REFERENCES DOCTOR(EmployeeID),
    FOREIGN KEY (Fac_ID) REFERENCES FACILITY(Facility_ID),
    FOREIGN KEY (In_ID) REFERENCES INVOICE(Inv_ID)
);
