-- Active: 1713861330832@@127.0.0.1@3306@MHS
DROP TABLE IF EXISTS MAKES_APPOINTMENT;
DROP TABLE IF EXISTS TREATS;
DROP TABLE IF EXISTS INVOICE_DETAIL;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS DOCTOR;
DROP TABLE IF EXISTS NURSE;
DROP TABLE IF EXISTS OTHER_HCP;
DROP TABLE IF EXISTS ADMIN_STAFF;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS OUTPATIENT_SURGERY;
DROP TABLE IF EXISTS OFFICE_BUILDING;
DROP TABLE IF EXISTS FACILITY;
DROP TABLE IF EXISTS INSURANCE_COMPANY;

CREATE TABLE FACILITY (
    Facility_ID INT AUTO_INCREMENT PRIMARY KEY,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    State VARCHAR(2) NOT NULL,
    Zip VARCHAR(10) NOT NULL,
    MaxSize INT,
    Facility_Type VARCHAR(50) NOT NULL,
    CHECK (Facility_Type IN ('OP Surgery', 'Office'))
);

CREATE TABLE INSURANCE_COMPANY (
    InsuranceComp_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    State VARCHAR(2) NOT NULL,
    Zip VARCHAR(10) NOT NULL
);

CREATE TABLE EMPLOYEE (
    EmployeeID INT AUTO_INCREMENT PRIMARY KEY,
    SSN CHAR(9) UNIQUE NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    MiddleName VARCHAR(255),
    LastName VARCHAR(255) NOT NULL,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    State VARCHAR(255) NOT NULL,
    Zip VARCHAR(10) NOT NULL,
    Salary DECIMAL(10, 2) CHECK (Salary >= 0),
    Date_Hired DATE NOT NULL,
    Job_Class VARCHAR(50) NOT NULL,
    Fac_ID INT NOT NULL,
    FOREIGN KEY (Fac_ID) REFERENCES FACILITY(Facility_ID),
    CHECK (SSN REGEXP '^[0-9]{9}$'),
    CHECK (Job_Class IN ('Doctor', 'Nurse', 'HCP', 'Admin'))
);