-- Active: 1713861330832@@127.0.0.1@3306@MHS
SELECT d.EmployeeID, e.FirstName, e.LastName 
FROM DOCTOR d
JOIN EMPLOYEE e ON d.EmployeeID = e.EmployeeID;

SELECT * FROM PATIENT;

SELECT * FROM INSURANCE_COMPANY;

SELECT * FROM FACILITY;

SELECT * FROM INSURANCE_COMPANY WHERE Name = 'GoodHealth Ins';

SELECT * FROM MAKES_APPOINTMENT;