SELECT INVOICE.InComp_ID, AVG(INVOICE_DETAIL.Cost) AS Average_Daily_Revenue
FROM INVOICE
JOIN INVOICE_DETAIL ON INVOICE.Inv_ID = INVOICE_DETAIL.Inv_ID
WHERE INVOICE.InvDate BETWEEN '2024-05-01' AND '2024-05-03' 
GROUP BY INVOICE.InComp_ID;